### PR TITLE
Enhanced chatting

### PR DESCRIPTION
**Pull request by multimokia**
# Enhanced Chatting
Adds richer markdown support and enhances some styles for many markdown items

## API Changes:
- Messages can now be multiline
- Images auto embed from links
- Links now have a blue color
- Headers 1-6 are functional
- Ordered lists work properly (also take an indent)
- Unordered lists are automatically converted to bullet points (instead of dashes, also take an indent)
- Lists can be nested using an indent of **4** spaces
- Tables are supported in syntax
- Checkboxes are also supported
- Auto links are supported
- Codeblocks are functional (see remark highlight for supported languages)
- LaTeX support (math expressions), use `$expression$` for single-line, and `$$expression$$` for multiline
- Edited messages now have an `(edited)` annotation on them
- Delete/Update events are now listening for messages and the chat will update appropriately
- All links have a tooltip showing the real location of the anchor tag (this is to de-obfuscate masked links as a security measure)

### Packages Added:
- react-markdown
- remark-gfm
- rehype-highlight
- remark-math
- rehype-katex
- remark-breaks
- react-tooltip

## Known Issues:
- Textbox allows for infinite resizing (this should be limited in future)
- Weird corner square between horizontal/vertical scrollbar
- Checkboxes cannot be selected/de-selected by anyone unless the message is edited (this can be addressed in future to work similarly to GitHub, but is not pressing at this moment)

## Notes:
Here is a markdown reference for testing
sorry I should have thrown this in the PR desc, here's an outline:
```md
# Header 1
## Header 2
### Header 3
#### Header 4
##### Header 5
###### Header 6

- Unordered List
- Unordered lists can also be achieved using `*` instead of `-`

1. Ordered List
2. This is another item in an ordered list

- [ ] This is an de-selected checkbox
- [X] This is a selected checkbox

[this is a masked link](https://www.youtube.com/watch?v=h5DiM8g894k)
![this would embed an image or video if the url points to one (note not Youtube, just a video file)](https://cdn.discordapp.com/attachments/1047327043290923118/1077553184307957810/2023-02-21_06-30-28.mkv)

> This is a blockquote

*italics*
**bold**
***bold + italics***
`inline codeblock`
\```python
def hello(to: str) -> str:
    """
    Docstring
    """
    print(f"Hello, {to}")
\```
```

### CODE REVIEW

**Review by jjensen-ai — CHANGES_REQUESTED** [review]
Most of the MD testing end up working there were a few things that did not 

**Bug 1** - Multi line messages did not work, but this could be something to do with macOS, or mac is seen as mobile maybe? 

**Bug 2** - Checkboxes would work if i copied and pasted from the readme, but if i tried to do them myself, they would not work. 

**Bug 3** - When you double tap the space bar on my computer it gives off a period

**Comment by multimokia** [comment]
> Most of the MD testing end up working there were a few things that did not
> 
> **Bug 1** - Multi line messages did not work, but this could be something to do with macOS, or mac is seen as mobile maybe?[^1]
> 
> **Bug 2** - Checkboxes would work if i copied and pasted from the readme, but if i tried to do them myself, they would not work.[^2]
> 
> **Bug 3** - When you double tap the space bar on my computer it gives off a period[^3]

[^1]: This is now addressed with the inclusion of `remark-breaks` and should be closer to the way the message was authored
[^2]: Slating this under wontfix, as this actually *isn't* part of the GitHub GFM spec, as this is common, I see no reason for us to support this either (as well, a user can easily edit their message to be of appropriate formatting)
[^3]: Client side only, and as discussed in Discord -- this is a feature of MacOS

**Review by jjensen-ai — APPROVED** [review]
:) everything works

**Review by Stan-l-e-y — APPROVED** [review]
all good in da hood

**Pull request merged**
